# Generated by Django 3.1a1 on 2020-05-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Agile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name='agile value name'
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Description of the Agile Value.',
                        verbose_name='agile value description',
                    ),
                ),
                (
                    'creation_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='date created'
                    ),
                ),
                (
                    'modified_date',
                    models.DateTimeField(
                        auto_now=True, verbose_name='date last modified'
                    ),
                ),
            ],
            options={'verbose_name_plural': 'Agile Values',},
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name='principle name'
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text='Description of the Agile Principle.',
                        verbose_name='principle description',
                    ),
                ),
                (
                    'creation_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='date created'
                    ),
                ),
                (
                    'modified_date',
                    models.DateTimeField(
                        auto_now=True, verbose_name='date last modified'
                    ),
                ),
            ],
            options={'verbose_name_plural': 'Principles',},
        ),
    ]
