# Generated by Django 3.1a1 on 2020-05-15 08:01

from django.db import migrations, models


def alter_agile_type(apps, schema_editor):
    """
    Update existing Agile instances with 'Value' type.
    """
    Agile = apps.get_model('main', 'Agile')
    TYPE_VALUE = 'value'
    for agile in Agile.objects.all():
        agile.type = TYPE_VALUE
        agile.save()


def move_principles_data(apps, schema_editor):
    """
    Create Agile instances with 'Principle' type.
    """
    Principle = apps.get_model('main', 'Principle')
    Agile = apps.get_model('main', 'Agile')
    TYPE_VALUE = 'value'
    TYPE_PRINCIPLE = 'principle'
    for principle in Principle.objects.all():
        Agile.objects.create(
            name=principle.name,
            description=principle.description,
            type=TYPE_PRINCIPLE,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agile',
            options={'verbose_name_plural': 'Agile Values and Principles'},
        ),
        migrations.AddField(
            model_name='agile',
            name='type',
            field=models.CharField(
                choices=[('value', 'Value'), ('principle', 'Principle')],
                default='value',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='agile',
            name='description',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Description of the Agile Value or Principle.',
                verbose_name='agile description',
            ),
        ),
        migrations.AlterField(
            model_name='agile',
            name='name',
            field=models.CharField(
                max_length=100, verbose_name='agile value/principle name'
            ),
        ),
        migrations.RunPython(alter_agile_type),
        migrations.RunPython(move_principles_data),
        migrations.DeleteModel(name='Principle',),
    ]
